export const COUNTRIES_AND_STATES = {
  India: [
    "Select State",
    "Tamil Nadu",
    "Kerala",
    "Karnataka",
    "Andhra Pradesh",
    "Telangana",
    "Maharashtra",
    "Delhi",
    "Gujarat",
    "West Bengal",
    "Uttar Pradesh",
    "Rajasthan",
    "Madhya Pradesh",
    "Punjab",
    "Haryana",
    "Bihar",
    "Odisha",
    "Assam",
    "Jharkhand",
    "Chhattisgarh",
    "Uttarakhand",
    "Himachal Pradesh",
    "Goa",
    "Tripura",
    "Manipur",
    "Meghalaya",
    "Nagaland",
    "Arunachal Pradesh",
    "Mizoram",
    "Sikkim",
    "Puducherry",
    "Chandigarh",
    "Jammu and Kashmir",
    "Ladakh",
    "All States",
  ],
  "United States": [
    "Select State",
    "California",
    "Texas",
    "Florida",
    "New York",
    "Illinois",
    "Pennsylvania",
    "Ohio",
    "Georgia",
    "North Carolina",
    "Michigan",
    "New Jersey",
    "Virginia",
    "Washington",
    "Arizona",
    "Massachusetts",
    "Tennessee",
    "Indiana",
    "Missouri",
    "Maryland",
    "Wisconsin",
    "Colorado",
    "Minnesota",
    "South Carolina",
    "Alabama",
    "Louisiana",
    "Kentucky",
    "Oregon",
    "Oklahoma",
    "Connecticut",
    "Utah",
    "Iowa",
    "Nevada",
    "Arkansas",
    "Mississippi",
    "Kansas",
    "New Mexico",
    "Nebraska",
    "Idaho",
    "West Virginia",
    "Hawaii",
    "New Hampshire",
    "Maine",
    "Rhode Island",
    "Montana",
    "Delaware",
    "South Dakota",
    "North Dakota",
    "Alaska",
    "Vermont",
    "Wyoming",
    "All States",
  ],
  "United Kingdom": [
    "Select State",
    "England",
    "Scotland",
    "Wales",
    "Northern Ireland",
    "Greater London",
    "West Midlands",
    "Greater Manchester",
    "West Yorkshire",
    "All Regions",
  ],
  "United Arab Emirates": [
    "Select State",
    "Dubai",
    "Abu Dhabi",
    "Sharjah",
    "Ajman",
    "Ras Al Khaimah",
    "Fujairah",
    "Umm Al Quwain",
    "All Emirates",
  ],
  Singapore: ["Select State", "Central Singapore", "North East", "North West", "South East", "South West", "All Regions"],
  Australia: [
    "Select State",
    "New South Wales",
    "Victoria",
    "Queensland",
    "Western Australia",
    "South Australia",
    "Tasmania",
    "Australian Capital Territory",
    "Northern Territory",
    "All States",
  ],
  Canada: [
    "Select State",
    "Ontario",
    "Quebec",
    "British Columbia",
    "Alberta",
    "Manitoba",
    "Saskatchewan",
    "Nova Scotia",
    "New Brunswick",
    "Newfoundland and Labrador",
    "All Provinces",
  ],
  Germany: ["Select State", "Bavaria", "Baden-Württemberg", "North Rhine-Westphalia", "Hesse", "Berlin", "Hamburg", "All States"],
  France: ["Select State", "Île-de-France", "Auvergne-Rhône-Alpes", "Nouvelle-Aquitaine", "Occitanie", "Hauts-de-France", "All Regions"],
  "Saudi Arabia": ["Select State", "Riyadh", "Makkah", "Eastern Province", "Madinah", "Asir", "All Regions"],
  Malaysia: ["Select State", "Selangor", "Kuala Lumpur", "Johor", "Penang", "Perak", "Sabah", "Sarawak", "All States"],
  "Sri Lanka": ["Select State", "Western Province", "Central Province", "Southern Province", "Northern Province", "All Provinces"],
  "Everywhere Else": ["Select State", "All Regions"],
};

export const ALL_COUNTRIES = Object.keys(COUNTRIES_AND_STATES);

/**
 * Detect country by user's public IP
 */
export async function detectCountryByIP() {
  try {
    const res = await fetch("https://ipapi.co/json/", { signal: AbortSignal.timeout(3000) });
    if (res.ok) {
      const data = await res.json();
      if (data.country_name && COUNTRIES_AND_STATES[data.country_name]) {
        return data.country_name;
      }
      if (data.country_name) {
        return data.country_name;
      }
    }
  } catch (e) {
    // fallback
  }
  return "India";
}
